package br.gov.bcb.scr2.operacional.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-03-16T15:48:43.995-03:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", name = "IScr2WebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IScr2WebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getResumoDoClienteBACEN", targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", className = "br.gov.bcb.scr2.operacional.webservice.GetResumoDoClienteBACEN")
    @WebMethod
    @ResponseWrapper(localName = "getResumoDoClienteBACENResponse", targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", className = "br.gov.bcb.scr2.operacional.webservice.GetResumoDoClienteBACENResponse")
    public br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente getResumoDoClienteBACEN(
        @WebParam(name = "codCliente", targetNamespace = "")
        java.lang.String codCliente,
        @WebParam(name = "tpCliente", targetNamespace = "")
        java.lang.String tpCliente,
        @WebParam(name = "dataBase", targetNamespace = "")
        java.lang.String dataBase,
        @WebParam(name = "cnpjIF", targetNamespace = "")
        java.lang.String cnpjIF,
        @WebParam(name = "autorizacao", targetNamespace = "")
        java.lang.String autorizacao
    ) throws BCServicoException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getResumoDoCliente", targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", className = "br.gov.bcb.scr2.operacional.webservice.GetResumoDoCliente")
    @WebMethod
    @ResponseWrapper(localName = "getResumoDoClienteResponse", targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", className = "br.gov.bcb.scr2.operacional.webservice.GetResumoDoClienteResponse")
    public br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente getResumoDoCliente(
        @WebParam(name = "codCliente", targetNamespace = "")
        java.lang.String codCliente,
        @WebParam(name = "tpCliente", targetNamespace = "")
        java.lang.String tpCliente,
        @WebParam(name = "dataBase", targetNamespace = "")
        java.lang.String dataBase,
        @WebParam(name = "autorizacao", targetNamespace = "")
        java.lang.String autorizacao
    ) throws BCServicoException_Exception;
}
