
package br.gov.bcb.scr2.operacional.webservice;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.16 2015-03-16T15:48:43.885-03:00 Generated source version: 2.6.16
 * 
 */
public final class IScr2WebService_Scr2WebPort_Client {

	@SuppressWarnings("unused")
	private static final QName SERVICE_NAME = new QName("http://webservice.operacional.scr2.bcb.gov.br/", "Scr2WebService");

	private IScr2WebService_Scr2WebPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		// URL wsdlURL = Scr2WebService.WSDL_LOCATION;
		// if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
		// File wsdlFile = new File(args[0]);
		// try {
		// if (wsdlFile.exists()) {
		// wsdlURL = wsdlFile.toURI().toURL();
		// } else {
		// wsdlURL = new URL(args[0]);
		// }
		// } catch (MalformedURLException e) {
		// e.printStackTrace();
		// }
		// }
		//
		// Scr2WebService ss = new Scr2WebService(wsdlURL, SERVICE_NAME);
		// IScr2WebService port = ss.getScr2WebPort();
		//
		// {
		// System.out.println("Invoking getResumoDoClienteBACEN...");
		// java.lang.String _getResumoDoClienteBACEN_codCliente = "";
		// java.lang.String _getResumoDoClienteBACEN_tpCliente = "";
		// java.lang.String _getResumoDoClienteBACEN_dataBase = "";
		// java.lang.String _getResumoDoClienteBACEN_cnpjIF = "";
		// java.lang.String _getResumoDoClienteBACEN_autorizacao = "";
		// try {
		// br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente _getResumoDoClienteBACEN__return =
		// port.getResumoDoClienteBACEN(_getResumoDoClienteBACEN_codCliente, _getResumoDoClienteBACEN_tpCliente,
		// _getResumoDoClienteBACEN_dataBase, _getResumoDoClienteBACEN_cnpjIF, _getResumoDoClienteBACEN_autorizacao);
		// System.out.println("getResumoDoClienteBACEN.result=" + _getResumoDoClienteBACEN__return);
		//
		// } catch (BCServicoException_Exception e) {
		// System.out.println("Expected exception: BCServicoException has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		// {
		// System.out.println("Invoking getResumoDoCliente...");
		// java.lang.String _getResumoDoCliente_codCliente = "";
		// java.lang.String _getResumoDoCliente_tpCliente = "";
		// java.lang.String _getResumoDoCliente_dataBase = "";
		// java.lang.String _getResumoDoCliente_autorizacao = "";
		// try {
		// br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente _getResumoDoCliente__return =
		// port.getResumoDoCliente(_getResumoDoCliente_codCliente, _getResumoDoCliente_tpCliente, _getResumoDoCliente_dataBase,
		// _getResumoDoCliente_autorizacao);
		// System.out.println("getResumoDoCliente.result=" + _getResumoDoCliente__return);
		//
		// } catch (BCServicoException_Exception e) {
		// System.out.println("Expected exception: BCServicoException has occurred.");
		// System.out.println(e.toString());
		// }
		// }
		//
		// System.exit(0);
	}

}
