
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.gov.bcb.scr2.operacional.webservice;

import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.6.16 2015-03-16T15:48:43.979-03:00 Generated source version: 2.6.16
 * 
 */

@javax.jws.WebService(serviceName = "Scr2WebService", portName = "Scr2WebPort", targetNamespace = "http://webservice.operacional.scr2.bcb.gov.br/", wsdlLocation = "", // Deixado
																																										// em
																																										// branco
																																										// porque
																																										// a
																																										// localizacao
																																										// do
																																										// WSDL
																																										// varia
																																										// entre
																																										// a
																																										// homologacao
																																										// e
																																										// a
																																										// producao
		endpointInterface = "br.gov.bcb.scr2.operacional.webservice.IScr2WebService")

public class IScr2WebServiceImpl implements IScr2WebService {

	// private static final Logger LOG = Logger.getLogger(IScr2WebServiceImpl.class.getName());
	Logger LOG = Logger.getLogger("BacenSCR");

	/*
	 * (non-Javadoc)
	 * 
	 * @see br.gov.bcb.scr2.operacional.webservice.IScr2WebService#getResumoDoClienteBACEN(java.lang.String codCliente ,)java.lang.String
	 * tpCliente ,)java.lang.String dataBase ,)java.lang.String cnpjIF ,)java.lang.String autorizacao )*
	 */
	public br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente getResumoDoClienteBACEN(java.lang.String codCliente,
			java.lang.String tpCliente, java.lang.String dataBase, java.lang.String cnpjIF, java.lang.String autorizacao)
			throws BCServicoException_Exception {
		LOG.info("Executing operation getResumoDoClienteBACEN");
		LOG.debug(codCliente);
		LOG.debug(tpCliente);
		LOG.debug(dataBase);
		LOG.debug(cnpjIF);
		LOG.debug(autorizacao);
		try {
			br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new BCServicoException_Exception("BCServicoException...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see br.gov.bcb.scr2.operacional.webservice.IScr2WebService#getResumoDoCliente(java.lang.String codCliente ,)java.lang.String
	 * tpCliente ,)java.lang.String dataBase ,)java.lang.String autorizacao )*
	 */
	public br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente getResumoDoCliente(java.lang.String codCliente,
			java.lang.String tpCliente, java.lang.String dataBase, java.lang.String autorizacao) throws BCServicoException_Exception {
		LOG.info("Executing operation getResumoDoCliente");
		LOG.debug(codCliente);
		LOG.debug(tpCliente);
		LOG.debug(dataBase);
		LOG.debug(autorizacao);
		try {
			br.gov.bcb.scr2.operacional.webservice.ResumoDoCliente _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new BCServicoException_Exception("BCServicoException...");
	}

}
